//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_PMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities1 : DbContext
    {
        public PMSEntities1()
            : base("name=PMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ForecastAnalysisResultFile> ForecastAnalysisResultFiles { get; set; }
        public virtual DbSet<ForecastChangeActionPlanFile> ForecastChangeActionPlanFiles { get; set; }
        public virtual DbSet<ForecastFilePath> ForecastFilePaths { get; set; }
        public virtual DbSet<ForecastPeriod> ForecastPeriods { get; set; }
        public virtual DbSet<ForecastPeriodCompetitorValue> ForecastPeriodCompetitorValues { get; set; }
        public virtual DbSet<ForecastPeriodDocFile> ForecastPeriodDocFiles { get; set; }
        public virtual DbSet<ForecastPeriodResultRemark> ForecastPeriodResultRemarks { get; set; }
        public virtual DbSet<ForecastPeriodToolAndMethod> ForecastPeriodToolAndMethods { get; set; }
        public virtual DbSet<ForecastTool> ForecastTools { get; set; }
        public virtual DbSet<ForecastValueAndRealValue> ForecastValueAndRealValues { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<ImportantIndicatorResultMeasurement> ImportantIndicatorResultMeasurements { get; set; }
        public virtual DbSet<ImportantIndicatorTargetMeasuerment> ImportantIndicatorTargetMeasuerments { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<IndicatorDetailStatu> IndicatorDetailStatus { get; set; }
        public virtual DbSet<IndicatorOwner> IndicatorOwners { get; set; }
        public virtual DbSet<IndicatorType> IndicatorTypes { get; set; }
        public virtual DbSet<IndicatorUnit> IndicatorUnits { get; set; }
        public virtual DbSet<IndicatorXIndicatorType> IndicatorXIndicatorTypes { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<PeriodMonthOrQuaterOrYear> PeriodMonthOrQuaterOrYears { get; set; }
        public virtual DbSet<PredictOwner> PredictOwners { get; set; }
        public virtual DbSet<SOEPlan> SOEPlans { get; set; }
        public virtual DbSet<SOEPlanIndicator> SOEPlanIndicators { get; set; }
        public virtual DbSet<StrategicObjective> StrategicObjectives { get; set; }
        public virtual DbSet<Strategy> Strategies { get; set; }
        public virtual DbSet<Tactic> Tactics { get; set; }
    }
}
