//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_PMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrategicObjective
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StrategicObjective()
        {
            this.Goals = new HashSet<Goal>();
            this.Strategies = new HashSet<Strategy>();
        }
    
        public int ID { get; set; }
        public Nullable<int> No { get; set; }
        public string StrategicObjective1 { get; set; }
        public Nullable<int> SOEPlanID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> Updateby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> isLastDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual SOEPlan SOEPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strategy> Strategies { get; set; }
    }
}
